### ISSUE TITLE
Websocket connection lost

### ISSUE THREAD

**Issue by longvision** [100mslive/100ms-web#686]
**Describe the bug**
Websocket connection being lost

**Project** 
react project sample adapted to next.js

**To Reproduce**

1. After leaving the previewScreen.jsx.
2. When joining entering the conference in the react app sample.
3. The websocket connection is lost.

**Expected behavior**
Should connect to the room.

**Screenshots**
![Screenshot 2023-11-17 080943](https://github.com/100mslive/100ms-web/assets/20291805/85c3f723-f77a-41c6-abc8-a7486d669826)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Brave and Chrome, same error on both
 - Version:
    -  Brave is up to date [Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)](https://brave.com/latest/)
    -  Chrome Version 119.0.6045.159 (Official Build) (64-bit)

**Additional context**
Started today

**Aditional error message in the console as well:**

[HMSPerformanceTiming] join-room-654940e77978e20a415f6dc0 
DOMException: Failed to execute 'measure' on 'Performance': The mark 'join-room-654940e77978e20a415f6dc0' does not exist.

rk 'join-room-654940e77978e20a415f6dc0' does not exist.
    at c.log (webpack-internal:///./node_modules/@100mslive/hms-video/dist/index.js:84:4120)
    at c.timeEnd (webpack-internal:///./node_modules/@100mslive/hms-video/dist/index.js:84:3690)
    at Pr.eval (webpack-internal:///./node_modules/@100mslive/hms-video/dist/index.js:135:157726)
    at Generator.next (<anonymous>)
    at s (webpack-internal:///./node_modules/@100mslive/hms-video/dist/index.js:60:794)

**Context:**
Solution was adapted to run on next.js and was running accordingly until yesterday.

**Comment by longvision** [comment]
Never Mind, I have found the problem.

I had an extra hsmActions.leave() inside the BackSwipe useEffect return function.
It was forcing the app to exit the room after entering in it.

**Comment by longvision** [comment]
code fixed on project end
